name: iOS CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        run: echo 'xcode-select -s /Applications/Xcode.app/Contents/Developer' | sudo bash

      - name: Install Xcode Command Line Tools
        run: xcode-select --install

      - name: Automatically select scheme and device
        id: prep
        run: |
          scheme=$(xcodebuild -list -json | jq -r '.project.targets[0]')
          device=$(xcrun simctl list devices available | grep -m1 iPhone | awk -F '[(]' '{print $1}' | xargs)
          echo "::set-output name=scheme::$scheme"
          echo "::set-output name=device::$device"

      - name: Build for Testing
        run: |
          xcodebuild build-for-testing -scheme ${{ steps.prep.outputs.scheme }} -destination "platform=iOS Simulator,name=${{ steps.prep.outputs.device }},OS=latest"

      - name: Run Tests
        run: |
          xcodebuild test-without-building -scheme ${{ steps.prep.outputs.scheme }} -destination "platform=iOS Simulator,name=${{ steps.prep.outputs.device }},OS=latest"
